"""
seed.py — 匯入初始地點資料
執行方式：python seed.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))

from app import create_app, db
from app.models.place import Place

PLACES = [
    {
        "name": "欣欣秀泰影城",
        "area": "中山",
        "category": "電影",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"約會\", \"雨天\", \"放鬆\", \"電影\", \"冷氣\", \"情侶\"]",
        "google_maps_url": "https://maps.app.goo.gl/JXeahY6UhRzgdPWk9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "林森公園",
        "area": "中山",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"野餐\", \"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/P9qHDwAEGtGLS9uw8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "富錦樹咖啡",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/R6gYH1WqwWFC8qmS7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "悄悄好食",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/89xh2FxTuyWPf6o39",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Hoto Cafe",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/7oMRBJkwQw16Hcbr9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "하반賀盤",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/4JNXWnUUNLDw1NWn9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "月里つきさと",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 3,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/w8YT6RqgXahVh4ZE9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "羊毛與花 ‧ 光點",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/QA93Phj5mzCAbuzd6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "卜卜商店",
        "area": "中山",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/GnKbtDeu7Snq5o4GA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "臺北當代藝術館",
        "area": "中山",
        "category": "展覽",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"文青\", \"藝術\", \"拍照\", \"質感\", \"室內\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/28j195DaxYfKXFqb7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "新光三越南西店",
        "area": "中山",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/4MyPRXgA137EzUjy7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "誠品生活南西店",
        "area": "中山",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/3wff4F7z6dVyJjdJ8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "心中山線形公園",
        "area": "中山",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"野餐\", \"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/s2mnmdqhHs5CG3nA6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "夏慕尼新香榭鐵板燒",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/sDgeQ4Spnbfdethz9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "螺絲瑪莉義麵坊",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/VLkrRBwPzux7Ju7D7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "義麵坊",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/HA86NUjpx6G6ueR77",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "台北晶華酒店栢麗廳",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/gwZHBKhW3hHQ6ayD8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "大倉久和大飯店歐風館",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/pwyLgKkuQd9BsAK86",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "台北老爺酒店Le Café",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/vfMLvBWh7EZvwVW59",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Does Art 都是藝術",
        "area": "中山",
        "category": "手作",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"互動感\", \"成品紀念\", \"不怕冷場\"]",
        "google_maps_url": "https://maps.app.goo.gl/TexbeVGrft3rQEBr9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "京站時尚廣場",
        "area": "中山",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/KMQTQjjZEn5xaP757",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "臺北京站威秀影城",
        "area": "中山",
        "category": "電影",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"約會\", \"雨天\", \"放鬆\", \"電影\", \"冷氣\", \"情侶\"]",
        "google_maps_url": "https://maps.app.goo.gl/SU8g7SPzjv4Bo48W7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "同位素酒吧Isotope bar",
        "area": "中山",
        "category": "酒吧",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/LqQvL2LhCiwSBQ376",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "青花驕麻辣鍋",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/N4MXZpZLAUprwste8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "袖珍博物館",
        "area": "中山",
        "category": "展覽",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"文青\", \"藝術\", \"拍照\", \"質感\", \"室內\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/dLP4QhaUbHb8vM95A",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "在室。甜點",
        "area": "中山",
        "category": "甜點",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"下午茶\", \"療癒\", \"拍照\", \"約會\", \"甜食\", \"文青\"]",
        "google_maps_url": "https://maps.app.goo.gl/spFyz1P1w4GgrHoD8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "FunLock放樂工作室",
        "area": "中山",
        "category": "遊戲",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 2,
        "max_people": 8,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"團隊合作\", \"刺激感\", \"腦力挑戰\"]",
        "google_maps_url": "https://maps.app.goo.gl/NZ9zGs6Cuvbsfxkh6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "遊域｜沉浸故事體驗館",
        "area": "中山",
        "category": "遊戲",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 4,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"團隊合作\", \"刺激感\", \"腦力挑戰\"]",
        "google_maps_url": "https://maps.app.goo.gl/xff8xYCTVns6Qg3F8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "吉星港式飲茶",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/exzbN4Rs3xCZcBPx9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "從前從前劇本館",
        "area": "中山",
        "category": "遊戲",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 6,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"團隊合作\", \"刺激感\", \"腦力挑戰\"]",
        "google_maps_url": "https://maps.app.goo.gl/WrGTknZL8cHYMLGq9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "PAI PAI CANNOLI｜義大利卡諾里",
        "area": "中山",
        "category": "甜點",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"下午茶\", \"療癒\", \"拍照\", \"約會\", \"甜食\", \"文青\"]",
        "google_maps_url": "https://maps.app.goo.gl/gwBtAuSLF4yyCtYs9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "青葉台灣料理",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/YcRvCTU72aunGNkL9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "ADDICT沉癮餐酒館",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/JBJ8jLQpTDpC6vRp7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "深和足體養生館 養生館",
        "area": "中山",
        "category": "足療",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"放鬆\", \"舒壓\", \"休息\", \"療癒\", \"紓壓\", \"恢復體力\"]",
        "google_maps_url": "https://maps.app.goo.gl/zZqXPuVjNLC9gtmU8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "稲町家香料咖哩",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/s4aBUvEkdtZB7jEg9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "八百屋",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/m2BCU2CjNe3Lkd418",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "京都伊藤久右衛門",
        "area": "中山",
        "category": "甜點",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/tjxK6x4bbg7xLb9E7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "逐愛轉運站放感情餐酒館",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/5EJobiqSn1RkpkWh7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "王品牛排",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/cNHrvX1d26hVUVFR7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "蔣老爹愛吃鍋",
        "area": "中山",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/bRbRBYEvJstpKnTr7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "角 • 攀岩館",
        "area": "中山",
        "category": "攀岩",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"挑戰感\", \"運動\", \"熱血\", \"刺激\"]",
        "google_maps_url": "https://maps.app.goo.gl/2MHE115adYD2ffSKA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Boringearrings串珠教室",
        "area": "中山",
        "category": "手作",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 2,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"互動感\", \"成品紀念\", \"不怕冷場\"]",
        "google_maps_url": "https://maps.app.goo.gl/vpSNQJ5FWkf5nrbz7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "信義威秀影城",
        "area": "信義",
        "category": "電影",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"約會\", \"雨天\", \"放鬆\", \"電影\", \"冷氣\", \"情侶\"]",
        "google_maps_url": "https://maps.app.goo.gl/zJkDLXaZ5paw9DyP8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "新光三越台北信義新天地",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/JQSn4fGtQi7pipPR8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "MUVIE CINEMAS 台北松仁",
        "area": "信義",
        "category": "電影",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"約會\", \"雨天\", \"放鬆\", \"電影\", \"冷氣\", \"情侶\"]",
        "google_maps_url": "https://maps.app.goo.gl/Mha9mjY2j31XVRY97",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "麵屋千雲 信義101店",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/FAxHtfUerNQxsFkH9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "統一時代百貨 台北店",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/kyF4aPb38TqG8hGfA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "象山步道",
        "area": "信義",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"野餐\", \"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/hpFFZDKWb94yqXPp6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "松山文創園區",
        "area": "信義",
        "category": "展覽",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"文青\", \"藝術\", \"拍照\", \"質感\", \"室內\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/x7KUB1MULrGrjFn4A",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "台北101購物中心",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/oXkp6MTgFQjc3s7t7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "台北101觀景台",
        "area": "信義",
        "category": "觀景",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"城市氛圍\", \"拍照\", \"浪漫\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/43CpMz4jAiD7qn3y6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "佐藤咖哩",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/4MVNNTfK4K4DsVTc6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "微風南山",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/PnrtumcyR5aVvYGfA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "ATT4FUN",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/8HoXXdvyaSSo4sxh8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "品都串燒",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 2,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"台式浪漫\", \"小吃\", \"平價\", \"聊天\"]",
        "google_maps_url": "https://maps.app.goo.gl/YTJ7hQZbJR94Ztvf9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "國家鐵道博物館",
        "area": "信義",
        "category": "展覽",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"文青\", \"藝術\", \"拍照\", \"質感\", \"室內\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/TULtQxnwv9x1i7Nx7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "柒息地串燒居酒屋",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/EqpCsHKck4AGgzdu8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "四四南村",
        "area": "信義",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"早上\", \"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/fWVcb4zfe4X21EmN7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "臨江街觀光夜市",
        "area": "信義",
        "category": "夜市",
        "indoor": "室外",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"台式浪漫\", \"小吃\", \"平價\", \"散步\"]",
        "google_maps_url": "https://maps.app.goo.gl/CYC2ViVs3rstHcdL8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Rs電子競技館",
        "area": "信義",
        "category": "網咖",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"耍廢\", \"宅\", \"遊戲\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/Zg9vVDLQRHX9GrZu9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "戰國網日式e宿館",
        "area": "信義",
        "category": "網咖",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"耍廢\", \"宅\", \"遊戲\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/EKs5YnRWuohs4AET7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Bellavita",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/7tgCcQq1j67Zm9jg7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Arthere Café 上樓看看咖啡",
        "area": "信義",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/Q1XjgTAgukdsUU1i7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "富邦美術館",
        "area": "信義",
        "category": "展覽",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"文青\", \"藝術\", \"拍照\", \"質感\", \"室內\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/F2vX1t3epsDYUHCH7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "DREAM PLAZA",
        "area": "信義",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/7hRRNkjhoVAYjZxi8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Draft Land Xinyi",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室外",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/EpkPHF6xdyuht2Hv5",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "CÉ LA VI 台北",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室外",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/7nUSnexuc371UUTd7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Flare Taipei",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室外",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/creCEdDUSkY8AKHn9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Sleep No More",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室外",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/FvHuoaMwZvgPhain9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "IMAGE INHOUSE",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/hLDK3LSQ876rUhYPA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Fake Sober Taipei",
        "area": "信義",
        "category": "酒吧",
        "indoor": "室外",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"微醺\", \"夜生活\", \"聊天\", \"放鬆\", \"約會\", \"音樂\"]",
        "google_maps_url": "https://maps.app.goo.gl/GhYshinXZ3b9unXc7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "M One Cafe A11",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/GhSqiyfpWib7B9KU6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Second Floor",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/fJBYraBR1HFrtuNC7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "UMAMI金色三麥",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/rSXmGqUEhZj2prRq6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "旭集 和食集錦",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/KMGhNTQrz4Y9rmKz5",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "饗 A Joy",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/Fd6VVe74e73XEAMQA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "饗食天堂",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/tB2kXHKDzah8GSmK6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "老井極上燒肉",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/kQNu2gStshs6u3pbA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "辛殿麻辣鍋",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/S8GVvJkLWo9iKwoY7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "小小麥",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/w6i3KpqwB6qeKw2w7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "INPARADISE 饗饗",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/i6YJBi7qzrrqg9Q38",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "鴨覓 烤鴨餐廳",
        "area": "信義",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"質感\"]",
        "google_maps_url": "https://maps.app.goo.gl/bPBvQWtUr6ZHCyW59",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Everyday is a Gift 手作工作室",
        "area": "信義",
        "category": "手作",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 2,
        "suitable_duration": "[\"3小時以內\", \"半天\"]",
        "tags": "[\"互動感\", \"紀念\", \"不怕冷場\"]",
        "google_maps_url": "https://maps.app.goo.gl/hp8sLGjZR2GuqNk69",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "動物園",
        "area": "政大附近",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"動物\", \"療癒\", \"親子\", \"散步\", \"拍照\", \"半日遊\"]",
        "google_maps_url": "https://maps.app.goo.gl/A4Wrd6yc914BAhWR8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "貓空纜車",
        "area": "政大附近",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 6,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"動物\", \"療癒\", \"親子\", \"拍照\", \"半日遊\"]",
        "google_maps_url": "https://maps.app.goo.gl/Y9s8Sa3i7gxyrMTn6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "邀月茶坊",
        "area": "政大附近",
        "category": "甜點",
        "indoor": "皆可",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"下午茶\", \"療癒\", \"拍照\", \"約會\", \"甜食\", \"文青\"]",
        "google_maps_url": "https://maps.app.goo.gl/tsn3NsbNvtQ61MBv6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "山上豆花",
        "area": "政大附近",
        "category": "甜點",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"中午\", \"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"下午茶\", \"療癒\", \"拍照\", \"約會\", \"甜食\", \"文青\"]",
        "google_maps_url": "https://maps.app.goo.gl/dVaaFLH44nbiPjHR7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "木柵製冰所",
        "area": "政大附近",
        "category": "甜點",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"下午茶\", \"療癒\", \"拍照\", \"約會\", \"甜食\", \"文青\"]",
        "google_maps_url": "https://maps.app.goo.gl/XRZZb1SbPX9zfCRH9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "貓空 四爺 Sih Ye",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 4,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"和菜\"]",
        "google_maps_url": "https://maps.app.goo.gl/sRhF5E38Xus7tU6U8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "樟樹步道",
        "area": "政大附近",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/7r8nsd6FPSyrH69VA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "政大後山大草原",
        "area": "政大附近",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"野餐\", \"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/uwakYhTFGrvq5cku8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "自由・之丘",
        "area": "政大附近",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/NAgDS3wqxf2FTYLa9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "呼嚕小酒館 Purrson Bistro",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\"]",
        "google_maps_url": "https://maps.app.goo.gl/PX6E9L9YULbm2DJ96",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Jimmy on the road 居米先生在路上",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 2,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"日式\"]",
        "google_maps_url": "https://maps.app.goo.gl/4Sr4U2j2WY4bDKpo8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "裕隆城",
        "area": "政大附近",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/uiNqEGH7Cnv5TQ1v9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "新店威秀影城",
        "area": "政大附近",
        "category": "電影",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"約會\", \"雨天\", \"放鬆\", \"電影\", \"冷氣\", \"情侶\"]",
        "google_maps_url": "https://maps.app.goo.gl/QCDPh7fHvtjusvLm8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "自己做 烘焙聚樂部",
        "area": "政大附近",
        "category": "手作",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 2,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"互動感\", \"紀念\", \"不怕冷場\"]",
        "google_maps_url": "https://maps.app.goo.gl/ADeTgQ5ZCdN8fys99",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "景美夜市",
        "area": "政大附近",
        "category": "夜市",
        "indoor": "室外",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"台式浪漫\", \"小吃\", \"平價\", \"散步\"]",
        "google_maps_url": "https://maps.app.goo.gl/cCPXezwDKhYohwGJ9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "小廢墟咖啡",
        "area": "政大附近",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/ZK4E8VAqHdiJXrCDA",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "LAX 慵懶—貓空",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 500,
        "budget_max": 1000,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/MLBhMFpTvxo4g7Ym7",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "等一個人咖啡",
        "area": "政大附近",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/rK2x9xxA9Jqb28bX8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "新美河購物廣場",
        "area": "政大附近",
        "category": "購物",
        "indoor": "室內",
        "budget_min": 1000,
        "budget_max": 2000,
        "suitable_time": "[\"早上\", \"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"逛街\", \"購物\", \"美食\", \"冷氣\", \"雨天\"]",
        "google_maps_url": "https://maps.app.goo.gl/gQkiX9uq5PLUk67z9",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "目覺北城",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/kjeGs5pGz6ZGwJj96",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "道南河濱公園",
        "area": "政大附近",
        "category": "戶外活動",
        "indoor": "室外",
        "budget_min": 0,
        "budget_max": 0,
        "suitable_time": "[\"下午\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"半天\"]",
        "tags": "[\"野餐\", \"散步\", \"放空\", \"運動\", \"夕陽\", \"免費\"]",
        "google_maps_url": "https://maps.app.goo.gl/qZzXaRWG3RBk73G49",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "小曼谷泰國雲南料理",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 300,
        "budget_max": 500,
        "suitable_time": "[\"中午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/f7mGpLBUM5C5JeUj8",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "Jonnobi 關東煮",
        "area": "政大附近",
        "category": "餐廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 99,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"聚餐\", \"約會\", \"慶生\", \"打卡\", \"平價\"]",
        "google_maps_url": "https://maps.app.goo.gl/HMfsjtehLZF2JGy1A",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
    {
        "name": "the Second Half",
        "area": "政大附近",
        "category": "咖啡廳",
        "indoor": "室內",
        "budget_min": 0,
        "budget_max": 300,
        "suitable_time": "[\"中午\", \"下午\", \"晚上\"]",
        "companion_types": "[\"情侶\", \"朋友\", \"家人\", \"個人\"]",
        "min_people": 1,
        "max_people": 4,
        "suitable_duration": "[\"3小時以內\"]",
        "tags": "[\"讀書\", \"聊天\", \"安靜\", \"甜點\", \"文青\", \"約會\"]",
        "google_maps_url": "https://maps.app.goo.gl/M8xQWNg8T9zCyqWH6",
        "reason": "",
        "description": "",
        "image_url": "",
        "score": 4.0,
    },
]


def seed():
    app = create_app()
    with app.app_context():
        Place.query.delete()
        db.session.commit()
        for data in PLACES:
            db.session.add(Place(**data))
        db.session.commit()
        print(f"✅ 成功匯入 {len(PLACES)} 筆地點資料！")


if __name__ == "__main__":
    seed()