"""
seed.py — 匯入初始地點資料
執行方式：python seed.py
"""
import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

import json
from app import create_app, db
from app.models.place import Place

PLACES = [
    # ── 政大周邊 ────────────────────────────────────────────────
    {
        "name": "貓空纜車",
        "area": "政大周邊",
        "category": "景點",
        "description": "從動物園站搭纜車俯瞰台北盆地，全程約 25 分鐘，終點站可享貓空茶園風景。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 120, "budget_max": 120,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天","一整天"]',
        "reason": "高空纜車視野絕佳，適合拍照打卡，情侶特別推薦黃昏時段",
        "tags": '["景觀","拍照","浪漫"]',
        "lat": 24.9730, "lng": 121.5847,
        "address": "台北市文山區新光路二段8號",
        "image_url": "", "score": 4.5,
    },
    {
        "name": "貓空茶園（皇宮茶藝）",
        "area": "政大周邊",
        "category": "咖啡廳",
        "description": "山上茶園景觀茶館，提供文山包種茶、鐵觀音，可邊喝茶邊俯瞰台北。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["半天","一整天"]',
        "reason": "茶香配山景，慢活放鬆，適合悠閒的午後約會",
        "tags": '["慢活","景觀","文青"]',
        "lat": 24.9697, "lng": 121.5942,
        "address": "台北市文山區指南路三段40巷",
        "image_url": "", "score": 4.3,
    },
    {
        "name": "台北市立動物園",
        "area": "政大周邊",
        "category": "景點",
        "description": "亞洲最大動物園，貓熊館、企鵝館最受歡迎，適合半天到一整天遊覽。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 60, "budget_max": 60,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天","一整天"]',
        "reason": "超高 CP 值戶外景點，可愛動物讓氣氛輕鬆愉快",
        "tags": '["可愛","親子","低預算"]',
        "lat": 24.9994, "lng": 121.5804,
        "address": "台北市文山區新光路二段30號",
        "image_url": "", "score": 4.4,
    },
    {
        "name": "木柵公園（指南宮步道）",
        "area": "政大周邊",
        "category": "景點",
        "description": "沿指南宮步道健行，山頂可遠眺台北盆地，來回約 1.5 小時。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "免費健行，流汗之後更有話聊，適合喜歡戶外的情侶",
        "tags": '["免費","健行","運動"]',
        "lat": 24.9756, "lng": 121.5819,
        "address": "台北市文山區指南路三段",
        "image_url": "", "score": 4.0,
    },
    {
        "name": "樂法 le Phare 咖啡",
        "area": "政大周邊",
        "category": "咖啡廳",
        "description": "政大附近文青風咖啡館，甜點精緻，適合讀書或安靜約會。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 300,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "安靜舒適，很適合深度聊天或單純享受甜點時光",
        "tags": '["文青","甜點","安靜"]',
        "lat": 24.9873, "lng": 121.5762,
        "address": "台北市文山區羅斯福路六段",
        "image_url": "", "score": 4.2,
    },
    {
        "name": "新店碧潭",
        "area": "政大周邊",
        "category": "景點",
        "description": "碧潭吊橋旁的湖畔公園，可租雙人天鵝船，夜晚燈光浪漫。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 200,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "天鵝船超浪漫，夜晚水面倒影美，是情侶必去的台北秘境",
        "tags": '["浪漫","水景","夜晚"]',
        "lat": 24.9602, "lng": 121.5428,
        "address": "新北市新店區碧潭路",
        "image_url": "", "score": 4.3,
    },
    {
        "name": "政大附近羅斯福路美食街",
        "area": "政大周邊",
        "category": "餐廳",
        "description": "羅斯福路六段聚集各式平價美食：越南河粉、日式定食、台式便當，學生超友善。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 80, "budget_max": 200,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "學生錢包友善，選擇多元，輕鬆解決一餐",
        "tags": '["低預算","平價","方便"]',
        "lat": 24.9871, "lng": 121.5748,
        "address": "台北市文山區羅斯福路六段",
        "image_url": "", "score": 3.8,
    },

    # ── 信義商圈 ────────────────────────────────────────────────
    {
        "name": "台北 101 觀景台",
        "area": "信義",
        "category": "景點",
        "description": "89 樓室內觀景台，360 度俯瞰台北，天氣好時可見淡水河出海口。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 600, "budget_max": 600,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "台北最高點，夜景尤其震撼，適合想製造特別回憶的約會",
        "tags": '["夜景","打卡","難忘"]',
        "lat": 25.0339, "lng": 121.5645,
        "address": "台北市信義區信義路五段7號",
        "image_url": "", "score": 4.5,
    },
    {
        "name": "信義區 ATT 4 Fun 餐廳樓層",
        "area": "信義",
        "category": "餐廳",
        "description": "ATT 4 Fun 高樓層聚集多家主題餐廳，包含日式燒肉、義式、港式飲茶等。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 400, "budget_max": 900,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 12,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "多樣選擇讓選擇困難症秒治癒，環境舒適適合慶祝",
        "tags": '["美食","多元","慶祝"]',
        "lat": 25.0380, "lng": 121.5658,
        "address": "台北市信義區松壽路12號",
        "image_url": "", "score": 4.0,
    },
    {
        "name": "信義區電影院（威秀/國賓）",
        "area": "信義",
        "category": "活動",
        "description": "信義計劃區有威秀影城、國賓影城，最新院線電影應有盡有。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 300, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "電影是經典約會選項，氣氛自然，不用擔心話題冷場",
        "tags": '["電影","室內","輕鬆"]',
        "lat": 25.0364, "lng": 121.5648,
        "address": "台北市信義區松壽路19號",
        "image_url": "", "score": 4.1,
    },
    {
        "name": "象山步道",
        "area": "信義",
        "category": "景點",
        "description": "從象山步道頂端可正面欣賞台北 101，夜晚燈光超美，是最佳 IG 打卡點。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "免費、夜景極美，爬完後成就感讓對話更熱絡",
        "tags": '["免費","夜景","健行","打卡"]',
        "lat": 25.0268, "lng": 121.5766,
        "address": "台北市信義區信義路五段150巷",
        "image_url": "", "score": 4.6,
    },
    {
        "name": "誠品信義旗艦店",
        "area": "信義",
        "category": "活動",
        "description": "信義誠品 24 小時不打烊，書區、文創選品、展覽空間、咖啡廳一次滿足。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 300,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "文青感十足，書架間漫步很有約會氣氛，消費彈性大",
        "tags": '["文青","書店","文創"]',
        "lat": 25.0361, "lng": 121.5657,
        "address": "台北市信義區松高路11號",
        "image_url": "", "score": 4.3,
    },
    {
        "name": "微風南山廣場美食",
        "area": "信義",
        "category": "餐廳",
        "description": "信義區最新商場，B1–1F 聚集各式輕食、甜點、正餐，人氣超旺。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 600,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "新穎環境，選擇豐富，適合解決美食欲望",
        "tags": '["美食","新潮","打卡"]',
        "lat": 25.0343, "lng": 121.5641,
        "address": "台北市信義區松智路17號",
        "image_url": "", "score": 4.0,
    },
    {
        "name": "台北探索館",
        "area": "信義",
        "category": "活動",
        "description": "台北市府內免費博物館，以多媒體互動展示台北的城市發展歷史。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "免費又有深度，讓約會多一點文化感",
        "tags": '["免費","展覽","文化"]',
        "lat": 25.0400, "lng": 121.5648,
        "address": "台北市信義區市府路1號",
        "image_url": "", "score": 3.9,
    },

    # ── 中山 / 北車 ────────────────────────────────────────────
    {
        "name": "赤峰街散策",
        "area": "中山",
        "category": "景點",
        "description": "台北最文青的街道之一，老屋改造的選品店、咖啡館、二手唱片行林立。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 500,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "慢慢逛老街很有氣氛，每間店都是話題製造機",
        "tags": '["文青","老街","選品"]',
        "lat": 25.0543, "lng": 121.5215,
        "address": "台北市大同區赤峰街",
        "image_url": "", "score": 4.4,
    },
    {
        "name": "中山地下街（購物＋小吃）",
        "area": "中山",
        "category": "活動",
        "description": "連接台北車站到中山站的地下街，有服飾、文創、台式小吃，雨天首選。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 50, "budget_max": 300,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "不受天氣影響，逛逛買買很放鬆，適合隨性行程",
        "tags": '["購物","平價","室內"]',
        "lat": 25.0479, "lng": 121.5205,
        "address": "台北市中山區中山北路一段",
        "image_url": "", "score": 3.7,
    },
    {
        "name": "寧夏夜市",
        "area": "中山",
        "category": "餐廳",
        "description": "台北最道地的傳統夜市，蚵仔煎、花枝羹、古早味紅豆餅，在地人最愛。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 300,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "道地台灣味、邊走邊吃超有氣氛，適合想體驗在地生活的約會",
        "tags": '["夜市","台灣味","平價"]',
        "lat": 25.0547, "lng": 121.5162,
        "address": "台北市大同區寧夏路",
        "image_url": "", "score": 4.5,
    },
    {
        "name": "台北當代藝術館（MOCA）",
        "area": "中山",
        "category": "活動",
        "description": "位於中山的當代藝術館，展覽多元前衛，票價親切，適合喜歡藝術的朋友。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 50, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "藝術展覽提供很多話題，適合喜歡有深度對話的約會",
        "tags": '["藝術","展覽","文青"]',
        "lat": 25.0488, "lng": 121.5220,
        "address": "台北市大同區長安西路39號",
        "image_url": "", "score": 4.2,
    },
    {
        "name": "林森北路酒吧街（微醺夜遊）",
        "area": "中山",
        "category": "活動",
        "description": "林森北路有多家風格各異的酒吧，適合夜晚輕鬆小酌，氣氛輕鬆熱鬧。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 600,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "微醺狀態讓雙方更放鬆，適合增進感情",
        "tags": '["夜晚","小酌","輕鬆"]',
        "lat": 25.0520, "lng": 121.5267,
        "address": "台北市中山區林森北路",
        "image_url": "", "score": 4.0,
    },
    {
        "name": "台北花博公園（美術館園區）",
        "area": "中山",
        "category": "景點",
        "description": "免費的都市公園，有大片草地、裝置藝術、台北市立美術館，適合野餐散步。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "台北市中心難得的大片綠地，帶著野餐墊和零食就是完美下午",
        "tags": '["野餐","公園","免費"]',
        "lat": 25.0720, "lng": 121.5213,
        "address": "台北市中山區玉門街1號",
        "image_url": "", "score": 4.3,
    },
    {
        "name": "台北市立美術館（北美館）",
        "area": "中山",
        "category": "活動",
        "description": "台灣最重要的當代美術館，常設展加特展，票價 30 元，CP 值極高。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 30, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 30,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "高品質藝術展覽，讓約會多了層次感，逛完很有成就感",
        "tags": '["藝術","展覽","低預算"]',
        "lat": 25.0722, "lng": 121.5245,
        "address": "台北市中山區中山北路三段181號",
        "image_url": "", "score": 4.4,
    },
    {
        "name": "大稻埕碼頭夜景",
        "area": "中山",
        "category": "景點",
        "description": "淡水河畔的大稻埕碼頭，黃昏時有金光落日，夜晚涼風徐徐，超浪漫。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "免費的河畔浪漫，黃昏夕陽是天然濾鏡",
        "tags": '["免費","夕陽","浪漫","河畔"]',
        "lat": 25.0601, "lng": 121.5093,
        "address": "台北市大同區民生西路延平北路口",
        "image_url": "", "score": 4.5,
    },
    {
        "name": "迪化街老屋探索",
        "area": "中山",
        "category": "景點",
        "description": "台北保存最完整的清代街道，南北貨、中藥行、老屋咖啡館，很有歷史感。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 300,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "老街氛圍讓人放慢腳步，逛逛聊聊很自然",
        "tags": '["歷史","老街","文青"]',
        "lat": 25.0572, "lng": 121.5103,
        "address": "台北市大同區迪化街一段",
        "image_url": "", "score": 4.3,
    },
    {
        "name": "行天宮周邊（算命街＋吃晚餐）",
        "area": "中山",
        "category": "活動",
        "description": "行天宮附近的算命街，有趣文化體驗，附近有很多道地台式餐館。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起算命超有話題，笑著討論卦象讓感情升溫",
        "tags": '["獨特","話題","體驗"]',
        "lat": 25.0605, "lng": 121.5336,
        "address": "台北市中山區民權東路二段109號",
        "image_url": "", "score": 3.8,
    },
    {
        "name": "光點台北（老屋電影院）",
        "area": "中山",
        "category": "活動",
        "description": "日式老建築改建的藝術電影院，播放獨立電影和藝術片，附設咖啡館。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "質感老建築配藝術電影，是品味約會的最佳選擇",
        "tags": '["電影","文青","老建築"]',
        "lat": 25.0493, "lng": 121.5248,
        "address": "台北市中山區中山北路二段18號",
        "image_url": "", "score": 4.5,
    },
]


PLACES_EXTRA = [
    # ── 政大周邊（補充）────────────────────────────────────────
    {
        "name": "景美夜市",
        "area": "政大周邊",
        "category": "餐廳",
        "description": "距政大步行約 15 分鐘，平價小吃聚集，炸雞、臭豆腐、湯圓應有盡有。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 80, "budget_max": 200,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "政大學生最熟悉的夜市，邊走邊吃超有氣氛",
        "tags": '["夜市","平價","台灣味"]',
        "lat": 24.9981, "lng": 121.5446,
        "address": "台北市文山區景美街", "image_url": "", "score": 4.2,
    },
    {
        "name": "政大書城",
        "area": "政大周邊",
        "category": "活動",
        "description": "景美最大二手書店，藏書豐富，可以挖到絕版好書，價格親切。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 200,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "書堆裡意外翻到同款書，是最自然的話題開場",
        "tags": '["書店","文青","平價"]',
        "lat": 24.9979, "lng": 121.5442,
        "address": "台北市文山區景美街45號", "image_url": "", "score": 4.0,
    },
    {
        "name": "河堤公園（景美溪畔）",
        "area": "政大周邊",
        "category": "景點",
        "description": "景美溪旁的自行車道與河堤公園，適合散步、慢跑，視野開闊。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "免費的河畔散步，傍晚微風吹來超浪漫",
        "tags": '["免費","散步","自然"]',
        "lat": 24.9923, "lng": 121.5510,
        "address": "台北市文山區景美溪河堤", "image_url": "", "score": 4.0,
    },
    {
        "name": "木柵市場周邊小吃",
        "area": "政大周邊",
        "category": "餐廳",
        "description": "木柵傳統市場旁的在地早午餐，蛋餅、豆漿、燒餅，道地台式早餐文化。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 50, "budget_max": 150,
        "suitable_time": '["早上"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起吃早餐是最自然親密的約會形式",
        "tags": '["早餐","平價","在地"]',
        "lat": 24.9988, "lng": 121.5680,
        "address": "台北市文山區木柵路", "image_url": "", "score": 3.9,
    },
    {
        "name": "政大後山步道",
        "area": "政大周邊",
        "category": "景點",
        "description": "政大校園後方的山徑，輕鬆好走，沿途鳥鳴不斷，是政大學生的秘境。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "政大人的私房景點，邊爬邊聊天，汗水中更容易敞開心扉",
        "tags": '["免費","健行","秘境"]',
        "lat": 24.9888, "lng": 121.5801,
        "address": "台北市文山區政大校園後山", "image_url": "", "score": 4.1,
    },
    {
        "name": "仙跡岩步道",
        "area": "政大周邊",
        "category": "景點",
        "description": "景美附近的健行步道，頂端可眺望台北盆地，單程約 40 分鐘，難度低。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "免費健行，登頂後的視野讓人心情豁然開朗",
        "tags": '["免費","健行","景觀"]',
        "lat": 24.9941, "lng": 121.5495,
        "address": "台北市文山區景美仙跡岩", "image_url": "", "score": 4.3,
    },
    {
        "name": "貓空露天茶館",
        "area": "政大周邊",
        "category": "咖啡廳",
        "description": "貓空山上多家露天茶館，夜晚坐在戶外喝茶看台北夜景，極為浪漫。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["半天","一整天"]',
        "reason": "夜晚山上喝茶看夜景，是台北最浪漫的約會之一",
        "tags": '["浪漫","夜景","茶"]',
        "lat": 24.9701, "lng": 121.5951,
        "address": "台北市文山區指南路三段", "image_url": "", "score": 4.6,
    },
    {
        "name": "新店花園新城散步",
        "area": "政大周邊",
        "category": "景點",
        "description": "新店山城社區，有歐式建築風格街道，適合漫步拍照，氣氛清幽。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "台北少見的歐風街景，拍照超出片",
        "tags": '["拍照","散步","文青"]',
        "lat": 24.9612, "lng": 121.5398,
        "address": "新北市新店區花園新城", "image_url": "", "score": 4.1,
    },

    # ── 信義補充 ────────────────────────────────────────────────
    {
        "name": "四四南村",
        "area": "信義",
        "category": "景點",
        "description": "台北第一個眷村文化保存區，假日有市集，平日可免費參觀展覽。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 200,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "老眷村文化感十足，很有故事性，適合喜歡文化的約會",
        "tags": '["文化","免費","歷史"]',
        "lat": 25.0291, "lng": 121.5622,
        "address": "台北市信義區松勤街50號", "image_url": "", "score": 4.2,
    },
    {
        "name": "松山文創園區",
        "area": "信義",
        "category": "活動",
        "description": "舊菸廠改建的文創園區，有展覽、市集、設計商店，環境優美。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 300,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 30,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "文創氛圍濃厚，逛展覽讓約會有深度",
        "tags": '["文創","展覽","文青"]',
        "lat": 25.0440, "lng": 121.5609,
        "address": "台北市信義區光復南路133號", "image_url": "", "score": 4.4,
    },
    {
        "name": "信義區屋頂酒吧（AMBA）",
        "area": "信義",
        "category": "活動",
        "description": "信義區飯店屋頂酒吧，可俯瞰台北 101 夜景，調酒精緻，氣氛絕佳。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 400, "budget_max": 1000,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "屋頂夜景配調酒，是最有儀式感的約會體驗",
        "tags": '["夜景","調酒","浪漫"]',
        "lat": 25.0368, "lng": 121.5641,
        "address": "台北市信義區忠孝東路五段", "image_url": "", "score": 4.5,
    },
    {
        "name": "國父紀念館廣場",
        "area": "信義",
        "category": "景點",
        "description": "寬闊的廣場與綠地，可欣賞台北 101，傍晚常有街頭表演，免費入場。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "免費又開闊，傍晚吹風看 101 燈光超療癒",
        "tags": '["免費","散步","夜景"]',
        "lat": 25.0400, "lng": 121.5601,
        "address": "台北市信義區仁愛路四段505號", "image_url": "", "score": 4.1,
    },
    {
        "name": "信義區精品下午茶",
        "area": "信義",
        "category": "咖啡廳",
        "description": "信義區各大百貨頂樓或飯店提供精緻英式下午茶，適合慶祝特殊場合。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 800, "budget_max": 1500,
        "suitable_time": '["下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 6,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "精緻下午茶讓對方感受到用心，適合重要紀念日",
        "tags": '["奢華","下午茶","慶祝"]',
        "lat": 25.0364, "lng": 121.5660,
        "address": "台北市信義區", "image_url": "", "score": 4.3,
    },
    {
        "name": "吳興街美食聚落",
        "area": "信義",
        "category": "餐廳",
        "description": "信義區巷弄裡的平價美食街，有各式早午餐、便當、麵食，學生友善。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 80, "budget_max": 250,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "信義區難得的平價選擇，不用花大錢也能吃得好",
        "tags": '["平價","美食","學生"]',
        "lat": 25.0332, "lng": 121.5695,
        "address": "台北市信義區吳興街", "image_url": "", "score": 4.0,
    },
    {
        "name": "世貿中心展覽（依檔期）",
        "area": "信義",
        "category": "活動",
        "description": "台北世貿一館定期舉辦各類展覽，寵物展、動漫展、書展等，票價不一。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 400,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天"]',
        "reason": "根據對方興趣選展覽，展現你的用心",
        "tags": '["展覽","室內","多元"]',
        "lat": 25.0349, "lng": 121.5627,
        "address": "台北市信義區信義路五段5號", "image_url": "", "score": 4.0,
    },

    # ── 中山補充 ────────────────────────────────────────────────
    {
        "name": "中山商圈咖啡一條街",
        "area": "中山",
        "category": "咖啡廳",
        "description": "中山北路二段聚集多家質感咖啡館，從日系到歐式風格都有，適合午後漫遊。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 350,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "每家咖啡館都有自己的個性，逛完一家再換一家，超有趣",
        "tags": '["咖啡","文青","慢活"]',
        "lat": 25.0520, "lng": 121.5231,
        "address": "台北市中山區中山北路二段", "image_url": "", "score": 4.3,
    },
    {
        "name": "玻璃媽祖廟（行天宮）夜間參拜",
        "area": "中山",
        "category": "景點",
        "description": "行天宮夜間燈光莊嚴美麗，可以一起求籤問感情運勢，是特別的文化體驗。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起拜拜求籤，話題滿滿又有儀式感",
        "tags": '["免費","文化","夜晚"]',
        "lat": 25.0605, "lng": 121.5336,
        "address": "台北市中山區民權東路二段109號", "image_url": "", "score": 4.0,
    },
    {
        "name": "林森公園夜間散步",
        "area": "中山",
        "category": "景點",
        "description": "林森北路旁的綠帶公園，夜間燈光柔和，適合飯後散步消化。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "免費夜間散步，燈光浪漫，是飯後最自然的約會延伸",
        "tags": '["免費","夜晚","散步","浪漫"]',
        "lat": 25.0527, "lng": 121.5268,
        "address": "台北市中山區林森北路", "image_url": "", "score": 3.9,
    },
    {
        "name": "寧夏誠記越南麵食",
        "area": "中山",
        "category": "餐廳",
        "description": "中山區知名越南料理，河粉、春捲道地美味，CP 值超高，常常大排長龍。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 250,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "排隊等待的時間反而讓彼此多了聊天機會",
        "tags": '["異國料理","平價","美食"]',
        "lat": 25.0551, "lng": 121.5168,
        "address": "台北市大同區寧夏路附近", "image_url": "", "score": 4.3,
    },
    {
        "name": "台北當代藝術館附近老宅咖啡",
        "area": "中山",
        "category": "咖啡廳",
        "description": "MOCA 周邊有多家老屋改建的咖啡館，逛完展覽可以順道喝杯咖啡繼續聊。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 120, "budget_max": 280,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "老宅空間有故事感，喝咖啡聊展覽是最有質感的約會",
        "tags": '["咖啡","老宅","文青"]',
        "lat": 25.0490, "lng": 121.5222,
        "address": "台北市大同區長安西路附近", "image_url": "", "score": 4.2,
    },
    {
        "name": "大橋頭捷運站周邊老街",
        "area": "中山",
        "category": "景點",
        "description": "延三夜市與老街區，保留濃厚老台北生活感，有傳統糕餅店、古早味零食。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 50, "budget_max": 200,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "體驗老台北生活，一起買古早味零食邊走邊吃",
        "tags": '["老街","古早味","在地"]',
        "lat": 25.0613, "lng": 121.5128,
        "address": "台北市大同區延平北路三段", "image_url": "", "score": 4.0,
    },
    {
        "name": "台北孔廟與大龍峒",
        "area": "中山",
        "category": "景點",
        "description": "台北孔廟與保安宮相鄰，古蹟群聚，建築精緻，免費參觀，適合文化深度遊。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "免費的古蹟巡禮，了解台北歷史，讓約會更有深度",
        "tags": '["免費","文化","歷史","古蹟"]',
        "lat": 25.0749, "lng": 121.5131,
        "address": "台北市大同區大龍街275號", "image_url": "", "score": 4.2,
    },
    {
        "name": "酒吧街精釀啤酒體驗",
        "area": "中山",
        "category": "活動",
        "description": "中山區有多家台灣精釀啤酒專門店，可以試喝不同口味，認識台灣精釀文化。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 300, "budget_max": 700,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "試喝不同口味的啤酒，輕鬆有趣，話題自然不斷",
        "tags": '["啤酒","夜晚","輕鬆"]',
        "lat": 25.0521, "lng": 121.5270,
        "address": "台北市中山區林森北路附近", "image_url": "", "score": 4.1,
    },

    # ── 其他台北熱門區域 ────────────────────────────────────────
    {
        "name": "永康街散步",
        "area": "中山",
        "category": "景點",
        "description": "台北最知名的散步街道，各式餐廳、咖啡館、精品小店林立，四季皆宜。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 500,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "永康街每走幾步就有驚喜，逛街聊天最自然",
        "tags": '["散步","美食","文青"]',
        "lat": 25.0326, "lng": 121.5302,
        "address": "台北市大安區永康街", "image_url": "", "score": 4.5,
    },
    {
        "name": "師大夜市",
        "area": "中山",
        "category": "餐廳",
        "description": "師大路周邊夜市，有韓式料理、日式居酒屋、台灣小吃，學生氣息濃厚。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 300,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "學生氛圍讓人放鬆，多元選擇讓挑食者也能滿足",
        "tags": '["夜市","平價","學生"]',
        "lat": 25.0258, "lng": 121.5289,
        "address": "台北市大安區師大路", "image_url": "", "score": 4.2,
    },
    {
        "name": "大安森林公園野餐",
        "area": "中山",
        "category": "景點",
        "description": "台北市中心最大公園，大片草地適合野餐，假日常有街頭音樂演出。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 200,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "帶上野餐墊和零食，躺在草地上聊天是最療癒的約會",
        "tags": '["野餐","公園","免費","自然"]',
        "lat": 25.0299, "lng": 121.5349,
        "address": "台北市大安區新生南路二段1號", "image_url": "", "score": 4.5,
    },
    {
        "name": "西門町商圈",
        "area": "中山",
        "category": "活動",
        "description": "台北最熱鬧的年輕人聚集地，電影院、街頭表演、各式餐廳、潮流服飾。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 100, "budget_max": 600,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天","一整天"]',
        "reason": "活力充沛，各種娛樂選項讓約會不無聊",
        "tags": '["熱鬧","購物","電影"]',
        "lat": 25.0424, "lng": 121.5081,
        "address": "台北市萬華區西門町", "image_url": "", "score": 4.2,
    },
    {
        "name": "華山 1914 文創園區",
        "area": "中山",
        "category": "活動",
        "description": "舊酒廠改建的文創園區，有展覽、市集、電影院、特色餐廳，整天都有活動。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 400,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 30,
        "suitable_duration": '["半天","一整天"]',
        "reason": "文創氛圍讓約會有層次，戶外空間在夜晚也很有氣氛",
        "tags": '["文創","展覽","文青"]',
        "lat": 25.0444, "lng": 121.5296,
        "address": "台北市中正區八德路一段1號", "image_url": "", "score": 4.4,
    },
    {
        "name": "饒河街觀光夜市",
        "area": "中山",
        "category": "餐廳",
        "description": "台北知名觀光夜市，胡椒餅是必吃，攤位密集，熱鬧非凡。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 100, "budget_max": 300,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "邊走邊吃各種小吃，輕鬆熱鬧，是零壓力的約會",
        "tags": '["夜市","小吃","熱鬧"]',
        "lat": 25.0508, "lng": 121.5774,
        "address": "台北市松山區饒河街", "image_url": "", "score": 4.3,
    },
    {
        "name": "基隆廟口夜市（一日遊）",
        "area": "政大周邊",
        "category": "餐廳",
        "description": "從台北出發約 40 分鐘，基隆廟口是台灣最有名的夜市之一，天婦羅、鼎邊趖必吃。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["一整天"]',
        "reason": "特地為對方規劃基隆小旅行，展現用心與驚喜感",
        "tags": '["小旅行","夜市","海港"]',
        "lat": 25.1285, "lng": 121.7419,
        "address": "基隆市仁愛區仁三路", "image_url": "", "score": 4.4,
    },
    {
        "name": "陽明山花季健行",
        "area": "政大周邊",
        "category": "景點",
        "description": "陽明山國家公園，春天賞花、秋天芒草，全年皆有不同風景，多條步道可選。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天","一整天"]',
        "reason": "大自然中的約會讓人心曠神怡，花海中拍照超浪漫",
        "tags": '["健行","自然","花季"]',
        "lat": 25.1524, "lng": 121.5484,
        "address": "台北市士林區陽明山國家公園", "image_url": "", "score": 4.6,
    },
    {
        "name": "淡水老街與漁人碼頭",
        "area": "政大周邊",
        "category": "景點",
        "description": "淡水老街逛逛吃吃，再步行或搭接駁車到漁人碼頭看夕陽，是台北經典一日遊。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["一整天"]',
        "reason": "淡水夕陽是台北最美的免費風景之一，情侶必去",
        "tags": '["夕陽","海景","老街","浪漫"]',
        "lat": 25.1701, "lng": 121.4393,
        "address": "新北市淡水區中正路", "image_url": "", "score": 4.5,
    },
    {
        "name": "烏來溫泉與瀑布",
        "area": "政大周邊",
        "category": "景點",
        "description": "新北市烏來，有天然溫泉、烏來瀑布、泰雅族文化，是台北近郊最佳一日遊。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 200, "budget_max": 800,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["一整天"]',
        "reason": "一起泡溫泉是最快拉近距離的約會，瀑布景色加分",
        "tags": '["溫泉","自然","一日遊"]',
        "lat": 24.8672, "lng": 121.5538,
        "address": "新北市烏來區烏來街", "image_url": "", "score": 4.5,
    },
    {
        "name": "九份老街",
        "area": "政大周邊",
        "category": "景點",
        "description": "充滿日式懷舊風情的山城，紅燈籠、石階步道、海景茶館，是台灣最具代表性的景點之一。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 600,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["一整天"]',
        "reason": "九份夜景如夢似幻，是讓對方難忘的浪漫約會",
        "tags": '["夜景","老街","浪漫","拍照"]',
        "lat": 25.1093, "lng": 121.8442,
        "address": "新北市瑞芳區九份老街", "image_url": "", "score": 4.7,
    },
    {
        "name": "平溪天燈（十分老街）",
        "area": "政大周邊",
        "category": "活動",
        "description": "十分老街放天燈是台灣最獨特的體驗之一，一起寫下心願放飛，極具儀式感。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 200, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["一整天"]',
        "reason": "一起放天燈許願，是最有儀式感的約會體驗",
        "tags": '["天燈","儀式感","難忘","一日遊"]',
        "lat": 25.0388, "lng": 121.7778,
        "address": "新北市平溪區十分老街", "image_url": "", "score": 4.6,
    },
    {
        "name": "KTV 歡唱",
        "area": "信義",
        "category": "活動",
        "description": "信義區有多家連鎖 KTV，包廂私密，點餐方便，是下雨天最佳備案。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 200, "budget_max": 600,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 15,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "唱歌放鬆又歡樂，互相點歌了解彼此的品味",
        "tags": '["歡唱","室內","歡樂"]',
        "lat": 25.0364, "lng": 121.5648,
        "address": "台北市信義區", "image_url": "", "score": 4.1,
    },
    {
        "name": "桌遊咖啡館",
        "area": "中山",
        "category": "活動",
        "description": "中山區有多家桌遊咖啡館，提供數百款桌遊，適合不知道要做什麼的朋友聚會或約會。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 350,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "桌遊讓彼此展現個性，笑鬧中感情自然升溫",
        "tags": '["桌遊","室內","歡樂"]',
        "lat": 25.0502, "lng": 121.5228,
        "address": "台北市中山區", "image_url": "", "score": 4.2,
    },
    {
        "name": "密室逃脫",
        "area": "信義",
        "category": "活動",
        "description": "信義區有多家密室逃脫，劇情豐富、機關精巧，60 分鐘的冒險讓感情迅速升溫。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 400, "budget_max": 800,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "共同面對挑戰讓彼此更有默契，是最刺激的約會",
        "tags": '["冒險","室內","刺激"]',
        "lat": 25.0364, "lng": 121.5648,
        "address": "台北市信義區", "image_url": "", "score": 4.3,
    },
    {
        "name": "攀岩館體驗",
        "area": "中山",
        "category": "活動",
        "description": "台北市內有多家室內攀岩館，提供初學者課程，不需要任何經驗就能體驗。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 300, "budget_max": 600,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起挑戰新事物，互相鼓勵讓感情更緊密",
        "tags": '["運動","冒險","室內"]',
        "lat": 25.0480, "lng": 121.5450,
        "address": "台北市中山區", "image_url": "", "score": 4.2,
    },
    {
        "name": "河濱公園騎自行車",
        "area": "政大周邊",
        "category": "活動",
        "description": "台北河濱自行車道超過 100 公里，可在景美、新店段租借 YouBike，沿河騎乘。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["半天","一整天"]',
        "reason": "並排騎車吹風，是最暢快的運動約會",
        "tags": '["騎車","運動","自然","免費"]',
        "lat": 24.9880, "lng": 121.5520,
        "address": "台北市文山區景美溪河濱", "image_url": "", "score": 4.3,
    },
    {
        "name": "台北市立天文科學教育館",
        "area": "中山",
        "category": "活動",
        "description": "士林區的天文館，有宇宙劇場、立體劇場，票價親切，適合喜歡科學的朋友。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 40, "budget_max": 120,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "一起仰望星空，聊宇宙的話題讓約會有深度",
        "tags": '["科學","展覽","低預算"]',
        "lat": 25.0944, "lng": 121.5240,
        "address": "台北市士林區基河路363號", "image_url": "", "score": 4.1,
    },
    {
        "name": "故宮博物院",
        "area": "中山",
        "category": "活動",
        "description": "世界四大博物館之一，翠玉白菜、毛公鼎等國寶必看，票價 350 元含常設展。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 350, "budget_max": 350,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人","個人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天","一整天"]',
        "reason": "世界級的文化體驗，讓約會充滿知識與美感",
        "tags": '["文化","展覽","歷史"]',
        "lat": 25.1022, "lng": 121.5484,
        "address": "台北市士林區至善路二段221號", "image_url": "", "score": 4.5,
    },
    {
        "name": "士林夜市",
        "area": "中山",
        "category": "餐廳",
        "description": "台北最大最知名的觀光夜市，美食選擇多元，從大腸包小腸到蚵仔煎應有盡有。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["3小時以內"]',
        "reason": "台北夜市文化的代表，多元美食讓每個人都滿足",
        "tags": '["夜市","小吃","熱鬧"]',
        "lat": 25.0877, "lng": 121.5240,
        "address": "台北市士林區大東路", "image_url": "", "score": 4.3,
    },
    {
        "name": "陽明山竹子湖賞花",
        "area": "政大周邊",
        "category": "景點",
        "description": "春天海芋季、夏天繡球花，竹子湖是台北近郊最美的賞花勝地，入園免費。",
        "indoor": False, "activity_type": "靜態",
        "budget_min": 0, "budget_max": 100,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 1, "max_people": 99,
        "suitable_duration": '["半天"]',
        "reason": "花海中漫步拍照，是最療癒的情侶約會",
        "tags": '["賞花","自然","浪漫"]',
        "lat": 25.1679, "lng": 121.5347,
        "address": "台北市北投區竹子湖路", "image_url": "", "score": 4.6,
    },
    {
        "name": "陽明山天母步道",
        "area": "政大周邊",
        "category": "景點",
        "description": "天母古道連結陽明山，沿途有瀑布、原始森林，是台北最受歡迎的健行路線之一。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 0, "budget_max": 0,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["半天","一整天"]',
        "reason": "免費健行，瀑布旁休息喝水，汗水中更容易敞開心扉",
        "tags": '["免費","健行","瀑布","自然"]',
        "lat": 25.1124, "lng": 121.5337,
        "address": "台北市士林區天母古道", "image_url": "", "score": 4.4,
    },
]



PLACES_SPECIFIC = [
    # ── 密室逃脫 ─────────────────────────────────────────────────
    {
        "name": "笨蛋工作室（安和店）",
        "area": "中山", "category": "活動",
        "description": "台北最知名密室逃脫品牌，平均每十個台北人就有一人玩過，主題多元場景精緻機關一流。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 400, "budget_max": 700,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "共同破解謎題讓默契大增，是創造難忘回憶的最佳約會",
        "tags": '["密室逃脫","刺激","解謎"]',
        "lat": 25.0339, "lng": 121.5506,
        "address": "台北市大安區安和路一段112巷27號B1", "image_url": "", "score": 4.6,
    },
    {
        "name": "邏思起子（信義館）",
        "area": "信義", "category": "活動",
        "description": "信義區密室逃脫，空間寬敞採光佳，有海盜、武俠、偵探主題，適合老手帶新手入坑。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 450, "budget_max": 700,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "場景精緻有電影感，適合想製造刺激回憶的情侶",
        "tags": '["密室逃脫","刺激","信義"]',
        "lat": 25.0263, "lng": 121.5701,
        "address": "台北市信義區松德路12-2號", "image_url": "", "score": 4.5,
    },
    {
        "name": "夢遊王國（創始館）",
        "area": "中山", "category": "活動",
        "description": "台北最具沉浸感的密室逃脫，可與NPC互動，劇情緊湊燒腦，3人立即成團，網友評價極高。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 600, "budget_max": 800,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 3, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "沉浸式體驗讓你們真正進入故事，創造最難忘的約會回憶",
        "tags": '["密室逃脫","沉浸","燒腦"]',
        "lat": 25.0574, "lng": 121.5119,
        "address": "台北市大同區延平北路二段202號3樓", "image_url": "", "score": 4.7,
    },
    {
        "name": "Miss GAME（松菸館）",
        "area": "信義", "category": "活動",
        "description": "位於松山文創園區的密室逃脫，文青風格環境，主題多元，適合喜歡有質感體驗的朋友。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 400, "budget_max": 650,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "文創園區的特殊氛圍讓密室體驗更有層次感",
        "tags": '["密室逃脫","文創","信義"]',
        "lat": 25.0440, "lng": 121.5609,
        "address": "台北市信義區光復南路133號南向製菸工廠", "image_url": "", "score": 4.4,
    },
    # ── 劇本殺 LARP ────────────────────────────────────────────
    {
        "name": "劇光燈 LARP（台北館）",
        "area": "中山", "category": "活動",
        "description": "台北最大劇本殺，場景媲美攝影棚，有換裝服務，最短150分鐘可玩，新手友善，主持人口碑極佳。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 500, "budget_max": 700,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 4, "max_people": 10,
        "suitable_duration": '["半天"]',
        "reason": "一起換裝扮演角色，笑鬧中感情自然升溫",
        "tags": '["劇本殺","角色扮演","換裝"]',
        "lat": 25.0424, "lng": 121.5081,
        "address": "台北市萬華區康定路46-3號", "image_url": "", "score": 4.6,
    },
    {
        "name": "謀殺衛斯理工作室",
        "area": "中山", "category": "活動",
        "description": "台北兩家分店，五大類劇本超過50個，場景服裝用心，主持人專業受好評，新手老手都適合。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 500, "budget_max": 700,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 4, "max_people": 10,
        "suitable_duration": '["半天"]',
        "reason": "劇本選擇多，可根據喜好選最適合的類型",
        "tags": '["劇本殺","推理","角色扮演"]',
        "lat": 25.0508, "lng": 121.5774,
        "address": "台北市松山區八德路四段245巷32弄42-2號", "image_url": "", "score": 4.5,
    },
    {
        "name": "410 號檔案室（中山）",
        "area": "中山", "category": "活動",
        "description": "全台LARP劇本數量第一，近400套劇本，有精緻服裝和環繞投影，是劇本殺重度玩家的天堂。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 500, "budget_max": 750,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 4, "max_people": 12,
        "suitable_duration": '["半天"]',
        "reason": "劇本最多，不管玩過多少次都能找到新故事",
        "tags": '["劇本殺","沉浸","推理"]',
        "lat": 25.0490, "lng": 121.5295,
        "address": "台北市中山區長安東路一段24-2號3F", "image_url": "", "score": 4.5,
    },
    # ── 攀岩 ──────────────────────────────────────────────────
    {
        "name": "角攀岩館（中山店）",
        "area": "中山", "category": "活動",
        "description": "台北人氣室內抱石攀岩館，路線豐富，平日約300元，初學者到進階者都適合，有金色指引箭頭設計。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 300, "budget_max": 350,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "一起挑戰攀岩互相鼓勵，汗水中感情升溫最快",
        "tags": '["攀岩","運動","挑戰"]',
        "lat": 25.0537, "lng": 121.5224,
        "address": "台北市中山區中山北路二段68號B1", "image_url": "", "score": 4.5,
    },
    {
        "name": "原岩攀岩館（明德店）",
        "area": "政大周邊", "category": "活動",
        "description": "台北知名抱石攀岩館，每月更新路線，提供技巧提升課程，從新手到老手都有適合的挑戰。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 300, "budget_max": 400,
        "suitable_time": '["早上","下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "每月新路線讓你們每次來都有新挑戰，持續創造共同記憶",
        "tags": '["攀岩","運動","挑戰"]',
        "lat": 25.1063, "lng": 121.5160,
        "address": "台北市北投區明德路", "image_url": "", "score": 4.4,
    },
    # ── 手作體驗 ──────────────────────────────────────────────
    {
        "name": "Pick & Collect 金工皮革",
        "area": "中山", "category": "活動",
        "description": "赤峰街人氣金工皮革手作教室，提供情侶款手鍊對戒課程，一對二上課，老師親切耐心。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 800, "budget_max": 1500,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 1, "max_people": 4,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "一起打造獨一無二的對戒或手鍊，是最有紀念價值的約會",
        "tags": '["手作","金工","紀念","情侶"]',
        "lat": 25.0543, "lng": 121.5212,
        "address": "台北市大同區赤峰街28之4號1F", "image_url": "", "score": 4.7,
    },
    {
        "name": "茁茁陶工作室",
        "area": "政大周邊", "category": "活動",
        "description": "文山區人氣陶藝教室，捏陶與手拉坏課程，距辛亥捷運站兩分鐘，可一起重現電影手拉坏片段。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 600, "budget_max": 1000,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起捏陶超解壓，帶回家的作品是最好的約會紀念",
        "tags": '["手作","陶藝","療癒"]',
        "lat": 24.9928, "lng": 121.5435,
        "address": "台北市文山區辛亥路四段166巷17號1樓", "image_url": "", "score": 4.5,
    },
    {
        "name": "春豬工作室（皮件）",
        "area": "中山", "category": "活動",
        "description": "大安區日式皮件手作工作室，提供鑰匙圈、筆袋等課程，老師細心，完成品質感十足。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 800, "budget_max": 1500,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "親手縫製皮件超療癒，帶走的成品獨一無二",
        "tags": '["手作","皮革","文青"]',
        "lat": 25.0302, "lng": 121.5338,
        "address": "台北市大安區青田街12巷12-2號", "image_url": "", "score": 4.4,
    },
    {
        "name": "下班隨手作（蠟燭課）",
        "area": "中山", "category": "活動",
        "description": "台北最多元的手作體驗，香氛蠟燭、乾燥花、水彩畫等50種課程，老師活潑，適合隨性報名。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 500, "budget_max": 900,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 20,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起做蠟燭，把心意藏進香氣裡",
        "tags": '["手作","蠟燭","香氛","療癒"]',
        "lat": 25.0480, "lng": 121.5220,
        "address": "台北市中山區", "image_url": "", "score": 4.3,
    },
    {
        "name": "光在金工（迪化街）",
        "area": "中山", "category": "活動",
        "description": "迪化街銀飾手作教室，復古舒適空間，可製作麻花線戒、愛心手環等情侶款，講師親切細心。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 800, "budget_max": 1500,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起打造對戒或手環，是最浪漫也最有紀念意義的約會",
        "tags": '["手作","銀飾","情侶","紀念"]',
        "lat": 25.0572, "lng": 121.5103,
        "address": "台北市大同區迪化街一段", "image_url": "", "score": 4.6,
    },
    # ── 甜點烘焙 ─────────────────────────────────────────────
    {
        "name": "自己做烘焙聚樂部",
        "area": "中山", "category": "活動",
        "description": "台北人氣烘焙體驗教室，蛋糕餅乾麵包DIY課程，手把手教學不需任何基礎，做完帶走品嚐。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 600, "budget_max": 1200,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 12,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "一起做甜點再一起吃掉，是最甜蜜的約會方式",
        "tags": '["烘焙","甜點","手作","療癒"]',
        "lat": 25.0480, "lng": 121.5220,
        "address": "台北市中山區", "image_url": "", "score": 4.4,
    },
    # ── 桌遊咖啡 ─────────────────────────────────────────────
    {
        "name": "未來桌遊咖啡（中山）",
        "area": "中山", "category": "活動",
        "description": "台北知名桌遊咖啡館，提供上千款桌遊，門票含飲料，有專人教學，適合不知道玩什麼的聚會。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "桌遊讓彼此展現真實個性，笑鬧中感情自然升溫",
        "tags": '["桌遊","室內","歡樂"]',
        "lat": 25.0502, "lng": 121.5228,
        "address": "台北市中山區", "image_url": "", "score": 4.3,
    },
    {
        "name": "骰子人桌遊（中山）",
        "area": "中山", "category": "活動",
        "description": "台北老字號桌遊咖啡館，環境舒適，從輕鬆到策略桌遊都有，適合各年齡層。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 350,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "老字號品質穩定，適合想輕鬆聊天又不無聊的約會",
        "tags": '["桌遊","室內","輕鬆"]',
        "lat": 25.0490, "lng": 121.5215,
        "address": "台北市中山區中山北路一段", "image_url": "", "score": 4.2,
    },
    # ── 水上活動 ─────────────────────────────────────────────
    {
        "name": "碧潭 SUP 立槳體驗",
        "area": "政大周邊", "category": "活動",
        "description": "新店碧潭SUP立式划槳體驗，翠綠湖面上一起划行，教練全程陪同，是台北最特別的水上約會。",
        "indoor": False, "activity_type": "動態",
        "budget_min": 500, "budget_max": 800,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 2, "max_people": 10,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "在水面上站立划行，刺激又浪漫，照片超好看",
        "tags": '["水上活動","SUP","戶外","刺激"]',
        "lat": 24.9602, "lng": 121.5428,
        "address": "新北市新店區碧潭", "image_url": "", "score": 4.5,
    },
    # ── 保齡球 ───────────────────────────────────────────────
    {
        "name": "京站保齡球館",
        "area": "中山", "category": "活動",
        "description": "台北車站旁現代化保齡球館，設備新穎，平日下午價格親切，是輕鬆有趣的室內約會。",
        "indoor": True, "activity_type": "動態",
        "budget_min": 200, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友","家人"]',
        "min_people": 2, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "互相指導姿勢、慶祝全倒，是笑聲最多的約會",
        "tags": '["保齡球","運動","歡樂"]',
        "lat": 25.0478, "lng": 121.5199,
        "address": "台北市大同區承德路一段1號", "image_url": "", "score": 4.0,
    },
    # ── SPA 按摩 ─────────────────────────────────────────────
    {
        "name": "信義區質感 SPA",
        "area": "信義", "category": "活動",
        "description": "信義商圈周邊多家質感SPA館，提供各式按摩療程，適合特別紀念日或約會後的放鬆。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 800, "budget_max": 2000,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","個人"]',
        "min_people": 1, "max_people": 4,
        "suitable_duration": '["3小時以內","半天"]',
        "reason": "一起放鬆身心，是最奢華也最療癒的約會體驗",
        "tags": '["SPA","按摩","放鬆","奢華"]',
        "lat": 25.0364, "lng": 121.5660,
        "address": "台北市信義區", "image_url": "", "score": 4.3,
    },
    # ── 調香體驗 ─────────────────────────────────────────────
    {
        "name": "巫婆的屋調香工作室",
        "area": "政大周邊", "category": "活動",
        "description": "新店半山腰療癒調香工作室，空間溫暖香氣怡人，帶你找到命定香味，附甜點享用，超適合放鬆。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 600, "budget_max": 1000,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 8,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起調出專屬香水，把對彼此的感覺化為香氣留存",
        "tags": '["手作","調香","療癒","浪漫"]',
        "lat": 24.9680, "lng": 121.5330,
        "address": "新北市新店區", "image_url": "", "score": 4.6,
    },
    # ── 早午餐 / 甜點 ────────────────────────────────────────
    {
        "name": "中山區文青早午餐",
        "area": "中山", "category": "餐廳",
        "description": "中山區集中大量質感早午餐店，從美式到台式應有盡有，假日悠閒Brunch是最自然的約會開場。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 200, "budget_max": 500,
        "suitable_time": '["早上","下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "悠閒吃頓早午餐，是最輕鬆自然的約會開始",
        "tags": '["早午餐","文青","輕鬆"]',
        "lat": 25.0530, "lng": 121.5230,
        "address": "台北市中山區", "image_url": "", "score": 4.2,
    },
    {
        "name": "信義區網紅甜點（微風南山）",
        "area": "信義", "category": "餐廳",
        "description": "微風南山集合多家人氣甜點品牌，草莓塔、千層、法式甜點一次滿足，信義最夯甜點朝聖地。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 400,
        "suitable_time": '["下午","晚上"]',
        "companion_types": '["情侶","朋友"]',
        "min_people": 1, "max_people": 6,
        "suitable_duration": '["3小時以內"]',
        "reason": "一起品嚐精緻甜點，是最甜蜜的約會午後",
        "tags": '["甜點","打卡","下午茶"]',
        "lat": 25.0343, "lng": 121.5641,
        "address": "台北市信義區松智路17號", "image_url": "", "score": 4.3,
    },
    {
        "name": "赤峰街甜點咖啡巡禮",
        "area": "中山", "category": "餐廳",
        "description": "赤峰街巷弄藏有多家質感甜點店和咖啡館，每間都有獨特個性，邊逛邊吃是文青約會最佳行程。",
        "indoor": True, "activity_type": "靜態",
        "budget_min": 150, "budget_max": 350,
        "suitable_time": '["下午"]',
        "companion_types": '["情侶","朋友","個人"]',
        "min_people": 1, "max_people": 4,
        "suitable_duration": '["3小時以內"]',
        "reason": "每間店都是驚喜，逛甜點店比逛街更有話聊",
        "tags": '["甜點","咖啡","文青","巷弄"]',
        "lat": 25.0543, "lng": 121.5215,
        "address": "台北市大同區赤峰街", "image_url": "", "score": 4.4,
    },
]

def seed():
    app = create_app()
    with app.app_context():
        # 清空舊資料
        Place.query.delete()
        db.session.commit()

        all_places = PLACES + PLACES_EXTRA + PLACES_SPECIFIC
        for data in all_places:
            place = Place(**data)
            db.session.add(place)

        db.session.commit()
        print(f"✅ 成功匯入 {len(all_places)} 筆地點資料！")


if __name__ == "__main__":
    seed()
